export const country = {
  "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia and Herzegowina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo",
  "CD": "Congo, the Democratic Republic of the",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Cote d'Ivoire",
  "HR": "Croatia (Hrvatska)",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "TP": "East Timor",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (Malvinas)",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "FX": "France, Metropolitan",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard and Mc Donald Islands",
  "VA": "Holy See (Vatican City State)",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran (Islamic Republic of)",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Korea, Democratic People's Republic of",
  "KR": "Korea, Republic of",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People's Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libyan Arab Jamahiriya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macau",
  "MK": "Macedonia, The Former Yugoslav Republic of",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia, Federated States of",
  "MD": "Moldova, Republic of",
  "MC": "Monaco",
  "MN": "Mongolia",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "AN": "Netherlands Antilles",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Reunion",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint LUCIA",
  "VC": "Saint Vincent and the Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia (Slovak Republic)",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia and the South Sandwich Islands",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SH": "St. Helena",
  "PM": "St. Pierre and Miquelon",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen Islands",
  "SZ": "Swaziland",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan, Province of China",
  "TJ": "Tajikistan",
  "TZ": "Tanzania, United Republic of",
  "TH": "Thailand",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UM": "United States Minor Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela",
  "VN": "Viet Nam",
  "VG": "Virgin Islands (British)",
  "VI": "Virgin Islands (U.S.)",
  "WF": "Wallis and Futuna Islands",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "YU": "Yugoslavia",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
};

export const region = {
  "republic-adygea": {
    name: "Адыгея республика",
    city: {
      "majkop": "Майкоп",
    }
  },
  "republic-altai": {
    name: "Алтай республика",
    city: {
      "belja": "Беля",
      "gorno-altajsk": "Горно-Алтайск",
      "katanda": "Катанда",
      "kosh-agach": "Кош-Агач",
      "kysyl-osek": "Кызыл-Озек",
      "ongudaj": "Онгудай",
      "turocak": "Турочак",
      "ust-kan": "Усть-Кан",
      "ust-koksa": "Усть-Кокса",
      "cemal": "Чемал",
      "shebalino": "Шебалино",
      "jajlju": "Яйлю",
    }
  },
  "altai-territory": {
    name: "Алтайский край",
    city: {
      "alejskaja": "Алейская",
      "baevo": "Баево",
      "barnaul": "Барнаул",
      "bijsk": "Бийск",
      "rijsk-zonalna": "Бийск-Зональная",
      "volciha": "Волчиха",
      "zarinsk": "Заринск",
      "zmeinogorsk": "Змеиногорск",
      "kamen-na-obi": "Камень-на-Оби",
      "kljuci": "Ключи",
      "krasnoscekovo": "Краснощеково",
      "pospeliha": "Поспелиха",
      "rebriha": "Ребриха",
      "rodino": "Родино",
      "rubcovsk": "Рубцовск",
      "slavgorod2": "Славгород",
      "soloneshnoe": "Солонешное",
      "talmenka": "Тальменка",
      "togul": "Тогул",
      "troickoe": "Троицкое",
      "uglovskoe": "Угловское",
      "habary": "Хабары",
      "celinnoe2": "Целинное",
      "charyshskoe": "Чарышское",
      "shelaboliha": "Шелаболиха",
    }
  },
  "amur-area": {
    name: "Амурская область",
    city: {
      "arhara": "Архара",
      "belogorsk": "Белогорск",
      "blagovescensk": "Благовещенск",
      "bomnak": "Бомнак",
      "bratoljubovka": "Братолюбовка",
      "byssa": "Бысса",
      "verhnjaja-tom": "Верхняя Томь",
      "dzalinda2": "Джалинда",
      "erofej-pavlovi": "Ерофей Павлович",
      "zavitaja": "Завитая",
      "zeja": "Зея",
      "ignasino": "Игнашино",
      "loksak": "Локшак",
      "lopcha": "Лопча",
      "magdagaci": "Магдагачи",
      "mazanovo": "Мазаново",
      "nora": "Нора",
      "norsk": "Норск",
      "pojarkovo": "Поярково",
      "svobodnyj": "Свободный",
      "sergeevka": "Сергеевка",
      "skovorodino": "Сковородино",
      "tynda": "Тында",
      "ust-njukza": "Усть-Нюкжа",
      "cernjaevo": "Черняево",
      "shevli": "Шевли",
      "simanovsk": "Шимановск",
      "ekimchan": "Экимчан",
    }
  },
  "arkhangelsk-area": {
    name: "Архангельская область",
    city: {
      "abramovskij-ma": "Абрамовский маяк",
      "arhangelsk": "Архангельск",
      "velsk": "Вельск",
      "verhnjaja-tojm": "Верхняя Тойма",
      "dvinskij-berez": "Двинской Березник",
      "emeck": "Емецк",
      "zizgin": "Жижгин",
      "im-m-v-popov": "Им. М.В. Попова",
      "kalgachiha": "Калгачиха",
      "kargopol": "Каргополь",
      "karpogory": "Карпогоры",
      "kojnas": "Койнас",
      "konevo": "Конево",
      "kotlas": "Котлас",
      "lesukonskoe": "Лешуконское",
      "mezen": "Мезень",
      "morgovec": "Моржовец",
      "moseevo": "Мосеево",
      "mudjug": "Мудьюг",
      "njandoma": "Няндома",
      "onega": "Онега",
      "pinega": "Пинега",
      "raznavolok": "Разнаволок",
      "severodvinsk": "Северодвинск",
      "sura": "Сура",
      "turcasovo": "Турчасово",
      "holmogory": "Холмогоры",
      "shangaly": "Шангалы",
      "senkursk": "Шенкурск",
      "jarensk": "Яренск",
    }
  },
  "astrakhan-area": {
    name: "Астраханская  область",
    city: {
      "astrahan": "Астрахань",
      "verhnij-baskun": "Верхний Баскунчак",
      "o-v-tjulenij": "Остров Тюлений",
      "harabali": "Харабали",
    }
  },
  "republic-bashkortostan": {
    name: "Башкортостан республика",
    city: {
      "akjar": "Акьяр",
      "bakaly": "Бакалы",
      "birsk": "Бирск",
      "duvan": "Дуван",
      "zilair": "Зилаир",
      "meleuz": "Мелеуз",
      "sterlitamak": "Стерлитамак",
      "ufa": "Уфа",
      "janaul": "Янаул",
    }
  },
  "belgorod-area": {
    name: "Белгородская область",
    city: {
      "belgorod": "Белгород",
      "valujki": "Валуйки",
      "gotnja": "Готня",
      "novyj-oskol": "Новый Оскол",
      "staryj-oskol": "Старый Оскол",
    }
  },
  "bryansk-area": {
    name: "Брянская область",
    city: {
      "brjansk": "Брянск",
      "zukovka": "Жуковка",
      "karachev": "Карачев",
      "krasnaja-gora": "Красная Гора",
      "trubcevsk": "Трубчевск",
      "unechja": "Унеча",
    }
  },
  "republic-buryatiya": {
    name: "Бурятия республика",
    city: {
      "babuskin": "Бабушкин",
      "bagdarin": "Багдарин",
      "barguzin": "Баргузин",
      "barguzinskij-z": "Баргузинский Заповедник",
      "bicura": "Бичура",
      "gorjacinsk": "Горячинск",
      "goudzhekit": "Гоуджекит",
      "zamokta": "Замакта",
      "kabansk": "Кабанск",
      "karaftit": "Карафтит",
      "kurumkan": "Курумкан",
      "kyren": "Кырен",
      "kjahta": "Кяхта",
      "mondy": "Монды",
      "muhorshibir": "Мухоршибирь",
      "nizhneangarsk": "Нижнеангарск",
      "novoselenginsk": "Новоселенгинск",
      "petropavlovka": "Петропавловка",
      "romanovka": "Романовка",
      "sanaga": "Санага",
      "sosnovo-ozersk": "Сосново-Озерское",
      "taksimo": "Таксимо",
      "tassa": "Тасса",
      "telemba": "Телемба",
      "tilishma": "Тилишма",
      "uakit": "Уакит",
      "ulanude": "Улан-Удэ",
      "ust-antose": "Усть-Антосе",
      "ust-barguzin": "Усть-Баргузин",
      "ust-zaza": "Усть-Заза",
      "horinsk": "Хоринск",
      "cakir": "Цакир",
    }
  },
  "vladimir-area": {
    name: "Владимирская область",
    city: {
      "aleksandrov": "Александров",
      "vladimir": "Владимир",
      "vjasniki": "Вязники",
      "gus-hrustaln": "Гусь-Хрустальный",
      "kovrov": "Ковров",
      "murom": "Муром",
      "petushki": "Петушки",
      "jurev-polski": "Юрьев-Польский",
    }
  },
  "volgograd-area": {
    name: "Волгоградская область",
    city: {
      "volgograd": "Волгоград",
      "voljskiy": "Волжский",
      "danilovka": "Даниловка",
      "elan": "Елань",
      "ilovlja": "Иловля",
      "kamysin": "Камышин",
      "mihaiylovka": "Михайловка",
      "nizhny-chir": "Нижний Чир",
      "pallasovka": "Паласовка",
      "serafimovic": "Серафимович",
      "urjupinsk": "Урюпинск",
      "frolovo": "Фролово",
      "elton": "Эльтон",
    }
  },
  "vologda-area": {
    name: "Вологодская область",
    city: {
      "babaevo": "Бабаево",
      "belozersk": "Белозерск",
      "velikij-ustjug": "Великий Устюг",
      "vozega": "Вожега",
      "vologda": "Вологда",
      "vytegra": "Вытегра",
      "nikolsk": "Никольск",
      "totma": "Тотьма",
      "cerepovec": "Череповец",
    }
  },
  "voronezh-area": {
    name: "Воронежская область",
    city: {
      "anna": "Анна",
      "bogucar": "Богучар",
      "borisoglebsk": "Борисоглебск",
      "voronez": "Воронеж",
      "kalac": "Калач",
      "liski": "Лиски",
      "pavlovsk": "Павловск",
    }
  },
  "republic-dagestan": {
    name: "Дагестан республика",
    city: {
      "ahty": "Ахты",
      "bujnaksk": "Буйнакск",
      "derbent": "Дербент",
      "kizljar": "Кизляр",
      "kocubej": "Кочубей",
      "mahackala": "Махачкала",
      "sergokala": "Сергокала",
      "hasavjurt": "Хасавюрт",
      "juzhno-suhokum": "Южно-Сухокумск",
    }
  },
  "evr-avt-obl": {
    name: "Еврейская автономная область",
    city: {
      "birobidzhan": "Биробиджан"
    }
  },
  "chita-area": {
    name: "Забайкальский край",
    city: {
      "aginskoe2": "Агинское",
      "aksa": "Акша",
      "aleksandrovski2": "Александровский з-д",
      "amazar": "Амазар",
      "balej": "Балей",
      "beklemishevo": "Беклемишево",
      "bolshaja-lepr": "Большая Лепринда",
      "borzja": "Борзя",
      "bukukun": "Букукун",
      "gorekacan": "Горекацан",
      "darasun": "Дарасун",
      "dono": "Доно",
      "zabajkalsk": "Забайкальск",
      "kajlastuj": "Кайластуй",
      "kalakan": "Калакан",
      "karymskaja": "Карымская",
      "katugino": "Катугино",
      "krasnyj-cikoj": "Красный Чикой",
      "ksenevskaja": "Ксеньевская",
      "kyker": "Кыкер",
      "kyra": "Кыра",
      "mangut": "Мангут",
      "menza": "Менза",
      "mogzon": "Могзон",
      "mogoca": "Могоча",
      "nercinsk": "Нерчинск",
      "nerchinskij-za": "Нерчинский Завод",
      "nizhij-casuche": "Нижний Цасучей",
      "nichatka": "Ничатка",
      "olovjannaja": "Оловянная",
      "petrovskij-zav": "Петровский Завод",
      "pokrovka": "Покровка",
      "priargunsk": "Приаргунск",
      "solovevsk": "Соловьевск",
      "srdnij-kalar": "Средний Калар",
      "srednjaja-olek": "Средняя Олекма",
      "sretensk": "Сретенск",
      "tungokocen": "Тунгокочен",
      "tupik": "Тупик",
      "ulety": "Улеты",
      "ust-kara2": "Усть-Кара",
      "ust-karenga": "Усть-Каренга",
      "usugli": "Усугли",
      "hilok": "Хилок",
      "hulugli": "Хулугли",
      "cara": "Чара",
      "cheremhovo2": "Черемхово",
      "chita": "Чита",
      "selopugino": "Шелопугино",
      "chilka": "Шилка",
      "jumurchen": "Юмурчен",
      "jamkun": "Ямкун",
    }
  },
  "ivanovo-area": {
    name: "Ивановская область",
    city: {
      "nvanovo": "Иваново",
      "kinesma": "Кинешма",
      "privolzhsk": "Приволжск",
      "jurevec": "Юрьевец",
    }
  },
  "republic-ingushetia": {
    name: "Ингушетия республика",
    city: {
      "nazran": "Назрань",
    }
  },
  "irkutsk-area": {
    name: "Иркутская область",
    city: {
      "alygdzer": "Алыгджер",
      "angarsk": "Ангарск",
      "arshan": "Аршан",
      "bajkalsk": "Байкальск",
      "balagansk": "Балаганск",
      "bajandaj": "Баяндай",
      "bodajbo": "Бодайбо",
      "bolshoe-golou": "Большое Голоустное",
      "bohan": "Бохан",
      "bratsk": "Братск",
      "verhnjaja-guta": "Верхняя Гутара",
      "erbogacen": "Ербогачен",
      "zigalovo": "Жигалово",
      "zalari": "Залари",
      "zajarsk": "Заярск",
      "zima": "Зима",
      "ika": "Ика",
      "inga": "Инга",
      "irkutsk": "Иркутск",
      "kazachinsk": "Казачинское",
      "kacug": "Качуг",
      "kirensk": "Киренск",
      "kultuk": "Култук",
      "mama": "Мама",
      "neroj": "Нерой",
      "nizneudinsk": "Нижнеудинск",
      "novochunka": "Новочунка",
      "orlik": "Орлик",
      "orlinga": "Орлинга",
      "o-bolshoy-ush": "Остров Большой Ушканий",
      "svetlyj": "Светлый",
      "solnethnaya": "Солнечная",
      "taezhaja": "Таежная",
      "tajshet": "Тайшет",
      "tanguj": "Тангуй",
      "tanhoj": "Танхой",
      "tompa": "Томпа",
      "tulun": "Тулун",
      "tunka": "Тунка",
      "tyrka": "Тырка",
      "usole-sibirsk": "Усолье-Сибирское",
      "ust-ilimsk": "Усть-Илимск",
      "ust-kut": "Усть-Кут",
      "ust-ordynskij": "Усть-Ордынский",
      "ust-uda": "Усть-Уда",
      "hamar-daban": "Хамар-Дабан",
      "chervjanka": "Червянка",
      "cheremhovo": "Черемхово",
    }
  },
  "republic-kabardino-balkaria": {
    name: "Кабардино-Балкария республика",
    city: {
      "nalcik": "Нальчик",
      "prohladnaja": "Прохладная",
    }
  },
  "kaliningrad-area": {
    name: "Калининградская область",
    city: {
      "baltijsk": "Балтийск",
      "zheleznodorozh": "Железнодорожный",
      "kaliningrad": "Калининград",
      "pionerskij": "Пионерский",
      "sovetsk": "Советск",
      "chernjahovsk": "Черняховск",
    }
  },
  "republic-kalmykia": {
    name: "Калмыкия республика",
    city: {
      "artesian": "Артезиан",
      "gorodovikovsk": "Городовиковск",
      "malye-derbety": "Малые Дербеты",
      "elista": "Элиста",
      "justa": "Юста",
      "jaskul": "Яшкуль",
    }
  },
  "kaluga-area": {
    name: "Калужская область",
    city: {
      "zhisdra": "Жиздра",
      "kaluga": "Калуга",
      "malojaroslavec": "Малоярославец",
      "mosalsk": "Мосальск",
      "obninsk": "Обнинск",
      "spas-demensk": "Спас-Деменск",
      "suhinici": "Сухиничи",
    }
  },
  "kamchatka-area": {
    name: "Камчатский край",
    city: {
      "apuka": "Апука",
      "bolsherechk": "Большерецк",
      "verhnee-penzin": "Верхнее Пенжино",
      "vodopadnaja": "Водопадная",
      "dolinovka": "Долиновка",
      "elizovo": "Елизово",
      "ica": "Ича",
      "kamenskoe": "Каменское",
      "kluchi": "Ключи",
      "kozyrevsk": "Козыревск",
      "korf": "Корф",
      "kronoki": "Кроноки",
      "mys-lopatka": "М. Лопатка",
      "milkovo": "Мильково",
      "mys-afrika": "Мыс Африка",
      "mys-osernoj": "Мыс Озерный",
      "nachiki": "Начики",
      "nikolskoe": "Никольское",
      "ozernaja": "Озерная",
      "oktjabrskaja": "Октябрьская",
      "ossora": "Оссора",
      "palana": "Палана",
      "petropavlovsk-": "Петропавловск-Камчатский",
      "petropavlovski": "Петропавловский Маяк",
      "puscino": "Пущино",
      "semjchik": "Семячик",
      "slautnoe": "Слаутное",
      "sosnovka": "Сосновка",
      "tevi": "Теви",
      "tigil": "Тигиль",
      "ustvajampolka": "Усть-Воямполка",
      "ust-kamcatsk": "Усть-Камчатск",
      "ust-hajrjuzov": "Усть-Хайрюзово",
      "chermunaut": "Чемурнаут",
      "esso": "Эссо",
    }
  },
  "republic-karachaevo-circassia": {
    name: "Карачаево-Черкесская республика",
    city: {
      "dombay": "Домбай",
      "kluhorskij-per": "Клухорский перевал",
      "cherkessk": "Черкесск",
    }
  },
  "republic-karelia": {
    name: "Карелия республика",
    city: {
      "gridino": "Гридино",
      "kalevala": "Калевала",
      "kem-port": "Кемь-Порт",
      "kolegma": "Колежма",
      "kondopoga": "Кондопога",
      "kugonavolok": "Куганаволок",
      "majachnyi": "Маячный",
      "medvezegorsk": "Медвежьегорск",
      "olonec": "Олонец",
      "o-valaam": "Остров  Валаам",
      "padany": "Паданы",
      "petrozavodsk": "Петрозаводск",
      "pudoz": "Пудож",
      "reboly": "Реболы",
      "segeza": "Сегежа",
      "sortavala": "Сортавала",
      "suojarvi": "Суоярви",
      "engozero": "Энгозеро",
      "juskozero": "Юшкозеро",
    }
  },
  "kemerovo-area": {
    name: "Кемеровская область",
    city: {
      "barsaz": "Барзас",
      "belovo": "Белово",
      "kemerovo": "Кемерово",
      "kiselevsk": "Киселевск",
      "kondoma": "Кондома",
      "krapivino": "Крапивино",
      "krasnoe": "Красное",
      "kusedeevo": "Кузедеево",
      "mariinsk": "Мариинск",
      "mezhdurechensk": "Междуреченск",
      "novokuznetsk": "Новокузнецк",
      "prokopevsk": "Прокопьевск",
      "promyshlennaja": "Промышленная",
      "tajga": "Тайга",
      "tisul": "Тисуль",
      "topki": "Топки",
      "tjazin": "Тяжин",
      "ust-kabyrza": "Усть-Кабырза",
      "centralnyj-ru": "Центральный рудник",
      "jurga": "Юрга",
      "jaja": "Яя",
    }
  },
  "kirov-area": {
    name: "Кировская область",
    city: {
      "vjatskie-polja": "Вятские Поляны",
      "darovskoe": "Даровское",
      "kilmes": "Кильмезь",
      "kirov": "Киров",
      "kirs": "Кирс",
      "kotelnic": "Котельнич",
      "kumeny": "Кумены",
      "lalsk": "Лальск",
      "nagorskoe": "Нагорское",
      "nolinsk": "Нолинск",
      "oparino": "Опарино",
      "uni": "Уни",
      "sabalino": "Шабалино",
      "jaransk": "Яранск",
    }
  },
  "republic-komi": {
    name: "Коми республика",
    city: {
      "vesljana": "Весляна",
      "vorkuta": "Воркута",
      "vuktyl": "Вуктыл",
      "izhma": "Ижма",
      "inta": "Инта",
      "kedva-vom": "Кедва-Вом",
      "koslan": "Кослан",
      "mutnyi-materik": "Мутный Материк",
      "objacevo": "Обьячево",
      "okunev-nos": "Окунев Нос",
      "petrun": "Петрунь",
      "pecora": "Печора",
      "pomozdino": "Помоздино",
      "pustosh": "Пустошь",
      "sosnogorsk": "Сосногорск",
      "syktyvkar": "Сыктывкар",
      "troicko-pecers": "Троицко-Печорское",
      "usinsk": "Усинск",
      "ust-kulom": "Усть-Кулом",
      "ust-usa": "Усть-Уса",
      "ust-cilma": "Усть-Цильма",
      "uhta": "Ухта",
      "jaksha": "Якша",
    }
  },
  "kostroma-area": {
    name: "Костромская область",
    city: {
      "buj": "Буй",
      "vohma": "Вохма",
      "kologriv": "Кологрив",
      "kostroma": "Кострома",
      "nikolo-poloma": "Николо-Полома",
      "pyscug": "Пыщуг",
      "sarja": "Шарья",
    }
  },
  "krasnodar-territory": {
    name: "Краснодарский край",
    city: {
      "anapa": "Анапа",
      "armavir": "Армавир",
      "belaja-glina": "Белая глина",
      "gelendzik": "Геленджик",
      "gorjacij-kljuc": "Горячий Ключ",
      "dzgugba": "Джубга",
      "dolzhanskaja": "Должанская",
      "ejsk": "Ейск",
      "kanevskaja": "Каневская",
      "krasnayapolyana": "Красная Поляна",
      "krasnodar": "Краснодар",
      "kropotkin": "Кропоткин",
      "krymsk": "Крымск",
      "kubanskaya": "Кубанская",
      "kuscevskaja": "Кущевская",
      "novorossijsk": "Новороссийск",
      "primorsko-ahta": "Приморско-Ахтарск",
      "slavjansk-nku": "Славянск-на-Кубани",
      "adler": "Сочи (Адлер)",
      "tihoreck": "Тихорецк",
      "tuapse": "Туапсе",
      "ust-labinsk": "Усть-Лабинск",
    }
  },
  "krasnoyarsk-territory": {
    name: "Красноярский край",
    city: {
      "aban": "Абан",
      "agata": "Агата",
      "aginskoe": "Агинское",
      "aleksandrovski": "Александровский Шлюз",
      "andrej": "Андрея",
      "artemovsk": "Артемовск",
      "achinsk": "Ачинск",
      "bajkit": "Байкит",
      "balahta": "Балахта",
      "bahta": "Бахта",
      "bogotol": "Боготол",
      "bogucany": "Богучаны",
      "bolsaja-murta": "Большая Мурта",
      "bolshoj-porog": "Большой Порог",
      "bolsoj-uluj": "Большой Улуй",
      "bor": "Бор",
      "vanavara": "Ванавара",
      "velmo": "Вельмо",
      "verescagino": "Верещагино",
      "verhneimbatsk": "Верхнеимбатск",
      "verhnij-amyl": "Верхний Амыл",
      "vorogovo": "Ворогово",
      "gmo-im-e-k-fe": "ГМО им. Е.К.Федорова",
      "dzerzinskoe": "Дзержинское",
      "dudinka": "Дудинка",
      "enisejsk": "Енисейск",
      "ermakovskoe": "Ермаковское",
      "essej": "Ессей",
      "igarka": "Игарка",
      "idrinskoe": "Идринское",
      "irbejskoe": "Ирбейское",
      "kasachinskoe": "Казачинское",
      "kasyr": "Казыр",
      "kansk": "Канск",
      "kantegir": "Кантегир",
      "karatuzskoe": "Каратузское",
      "kaca": "Кача",
      "kellog": "Келлог",
      "kemcug": "Кемчуг",
      "kerbo": "Кербо",
      "kodinsk": "Кодинск",
      "kolba": "Колба",
      "krasnojarsk": "Красноярск",
      "kresty-tajmyrs": "Кресты Таймырские",
      "kuzmovka": "Кузьмовка",
      "kuragino": "Курагино",
      "kureika": "Курейка",
      "lebjazhe2": "Лебяжье",
      "losinoborskoe": "Лосиноборское",
      "minusinsk": "Минусинск",
      "motygino": "Мотыгино",
      "m-sterligova": "Мыс Стерлигова",
      "nasarovo": "Назарово",
      "nazimovo": "Назимово",
      "nizhne-usinsko": "Нижне-Усинское",
      "novobiriljusy": "Новобирилюссы",
      "norilsk": "Норильск",
      "ozero-tajmyr": "Озеро Таймыр",
      "olenja-rechka": "Оленья Речка",
      "ostrov-dikson": "Остров Диксон",
      "pirovskoe": "Пировское",
      "poligus": "Полигус",
      "svetlolobovo": "Светлолобово",
      "severo-eniseji": "Северо-Енисейск",
      "sovetskaja-rec": "Советская Речка",
      "sopochnaj-karg": "Сопочная карга",
      "strelka": "Стрелка",
      "suhobuzimskoe": "Сухобузимское",
      "sym": "Сым",
      "tassevo": "Тасеево",
      "tura": "Тура",
      "turuhansk": "Туруханск",
      "tutonchany": "Тутончаны",
      "tjuhtet": "Тюхтет",
      "uzur": "Ужур",
      "ust-kamo": "Усть-Камо",
      "ust-usa2": "Усть-Уса",
      "uchami": "Учами",
      "ujar": "Уяр",
      "hatanga": "Хатанга",
      "chemdalsk": "Чемдальск",
      "shalinskoe": "Шалинское",
      "sharypovo": "Шарыпово",
      "shumicha": "Шумиха",
      "scetinkino": "Щетинкино",
      "janov-stan": "Янов Стан",
      "jarcevo": "Ярцево",
    }
  },
  "republic-krym": {
    name: "Крым республика",
    city: {
      "alupka": "Алупка",
      "alushta": "Алушта",
      "gurzuf": "Гурзуф",
      "evpatoria": "Евпатория",
      "kerch": "Керчь",
      "klepynine": "Клепинино",
      "koktebel": "Коктебель",
      "noviysvet": "Новый Свет (Крым)",
      "sevastopol": "Севастополь",
      "simferopol": "Симферополь",
      "sudak": "Судак",
      "feodosiia": "Феодосия",
      "chornomorske": "Черноморское",
      "yalta": "Ялта",
    }
  },
  "kurgan-area": {
    name: "Курганская область",
    city: {
      "dalmatovo": "Далматово",
      "zverinogolovsk": "Звериноголовское",
      "kataysk": "Катайск",
      "kurgan": "Курган",
      "kurtamys": "Куртамыш",
      "lebjazhe": "Лебяжье",
      "makusino": "Макушино",
      "pamjatnaja": "Памятная",
      "petuhovo": "Петухово",
      "polovinnoe": "Половинное",
      "celinnoe": "Целинное",
      "sadrinsk": "Шадринск",
      "satrovo": "Шатрово",
      "shumiha": "Шумиха",
    }
  },
  "kursk-area": {
    name: "Курская область",
    city: {
      "kursk": "Курск",
      "lgov": "Льгов",
      "novo-kastornoe": "Ново-Касторное",
      "obojan": "Обоянь",
      "ponyri": "Поныри",
      "rylsk": "Рыльск",
      "tim": "Тим",
    }
  },
  "leningrad-region": {
    name: "Ленинградская область",
    city: {
      "belogorka": "Белогорка",
      "vinnicy": "Винницы",
      "voznesene": "Вознесенье",
      "volosovo": "Волосово",
      "vyborg": "Выборг",
      "efimovskaja": "Ефимовская",
      "kingisepp": "Кингисепп",
      "kirishi": "Кириши",
      "lodejnoe-pole": "Лодейное поле",
      "lluga": "Луга",
      "nikolaevskoe": "Николаевская",
      "novaja-ladoga": "Новая Ладога",
      "ozerki": "Озерки",
      "petrokrepost": "Петрокрепость",
      "priozeorsk": "Приозерск",
      "sankt-peterburg": "Санкт-Петербург",
      "sosnovo": "Сосново",
      "tihvin": "Тихвин",
    }
  },
  "lipetsk-area": {
    name: "Липецкая область",
    city: {
      "elec": "Елец",
      "kon-kolodez": "Конь-Колодезь",
      "lev-tolstoj": "Лев Толстой",
      "lipeck": "Липецк",
    }
  },
  "magadan-area": {
    name: "Магаданская область",
    city: {
      "arka": "Арка",
      "arman": "Армань",
      "balygychan": "Балыгычан",
      "bohapcha": "Бохапча",
      "brohovo": "Брохово",
      "gizhiga": "Гижига",
      "dzheka-londona": "Джека Лондона",
      "kanon": "Каньон",
      "kegali": "Кегали",
      "kedon": "Кедон",
      "kulu": "Кулу",
      "labaznaja": "Лабазная",
      "magadan": "Магадан",
      "madaun": "Мадаун",
      "mys-alevina": "Мыс Алевина",
      "mys-bratev": "Мыс Братьев",
      "ola": "Ола",
      "omsukchan": "Омсукчан",
      "o-spafareva": "Остров  Спафарьева",
      "palatka": "Палатка",
      "sejmchan": "Сеймчан",
      "sovhoz-elgen": "Совхоз Эльген",
      "srednikan": "Средникан",
      "susuman": "Сусуман",
      "tajgonos": "Тайгонос",
      "talaja": "Талая",
      "talon": "Талон",
      "uega": "Уега",
      "ust-omchug": "Усть-Омчуг",
      "ushki": "Ушки",
      "hejdzhan": "Хейджан",
      "chelehova": "Шелехова",
      "jagodnoe": "Ягодное",
    }
  },
  "republic-mary-el": {
    name: "Марий Эл республика",
    city: {
      "joskar-ola": "Йошкар-Ола",
      "kozmodemjzns": "Козьмодемьянск",
      "morki": "Морки",
      "novyj-torjal": "Новый Торьял",
    }
  },
  "republic-mordovia": {
    name: "Мордовия республика",
    city: {
      "insar": "Инсар",
      "krasnoslobodsk": "Краснослободск",
      "saransk": "Саранск",
      "temnikov": "Темников",
      "torbeevo": "Торбеево",
    }
  },
  "moscow-area": {
    name: "Московская область",
    city: {
      "bykovo": "Быково",
      "vnukovo": "Внуково",
      "volokolamsk": "Волоколамск",
      "dmitrov": "Дмитров",
      "domodedowo": "Домодедово",
      "egorevsk": "Егорьевск",
      "kahira": "Кашира",
      "klin": "Клин",
      "kolomna": "Коломна",
      "mozaisk": "Можайск",
      "moscow": "Москва",
      "naro-fominsk": "Наро-Фоминск",
      "nemchinovka": "Немчиновка",
      "novo-jerusalim": "Ново-Иерусалим",
      "pavlovskij-pos": "Павловский Посад",
      "pavlovskoe": "Павловское",
      "sergiev-posad": "Сергиев Посад",
      "serpuhov": "Серпухов",
      "tretjakovo": "Третьяково",
      "cherusti": "Черусти",
      "sheremetevo": "Шереметьево",
    }
  },
  "murmansk-area": {
    name: "Мурманская область",
    city: {
      "apatity": "Апатиты",
      "vaijda-guba": "Вайда Губа",
      "verchove-r-lot": "Верховье р. Лотты",
      "guba-drozdovka": "Губа Дроздовка",
      "zarechensk": "Зареченск",
      "zacheek": "Зашеек",
      "kandalaksa": "Кандалакша",
      "kanevka": "Каневка",
      "kachkaranzy": "Кашкаранцы",
      "kirovsck": "Кировск",
      "kovda": "Ковда",
      "kovdor": "Ковдор",
      "kolmjavr": "Колмъявр",
      "krasnoscele": "Краснощелье",
      "lovozero": "Ловозеро",
      "moncegorsk": "Мончегорск",
      "murmansk": "Мурманск",
      "murmachi": "Мурмаши",
      "nivankjul": "Ниванкуль",
      "nikel": "Никель",
      "o-charlov": "Остров  Харлов",
      "padun": "Падун",
      "poljrnoe": "Полярный",
      "pjalica": "Пялица",
      "svjatoi-nos": "Святой Нос",
      "teriberka": "Териберка",
      "tumannaj": "Туманная",
      "umba": "Умба",
      "ura-guba": "Ура-Губа",
      "zyp-navolok": "Цып-Наволок",
      "chavanga": "Чаваньга",
      "janiskoski": "Янискоски",
    }
  },
  "nenetskij-ar": {
    name: "Ненецкий автономный округ",
    city: {
      "amderma": "Амдерма",
      "bugrino": "Бугрино",
      "indiga": "Индига",
      "kanin-nos": "Канин Нос",
      "kolguevb-sever": "Колгуев Северный",
      "kotkino": "Коткино",
      "mys-belyi-nos": "Мыс Белый Нос",
      "mys-konstantin": "Мыс Костантиновский",
      "mys-mikulkin": "Мыс Микулкин",
      "naryan-mar": "Нарьян-Мар",
      "nec": "Несь",
      "nignjaja-pesha": "Нижняя Пеша",
      "sengeiskii-cha": "Сенгейский Шар",
      "ust-kara": "Усть-Кара",
      "hodovariha": "Ходовариха",
      "chorei-ver": "Хорей-Вер",
      "hoseda-hard": "Хоседа-Хард",
      "sojna": "Шойна",
    }
  },
  "nizhegorodskaya-area": {
    name: "Нижегородская область",
    city: {
      "vetluga": "Ветлуга",
      "volzskaja-gmo": "Волжская ГМО",
      "voskresenskoe": "Воскресенское",
      "vyksa": "Выкса",
      "krasnye-baki": "Красные Баки",
      "lukojanov": "Лукоянов",
      "lyskovo": "Лысково",
      "niznij-novgoro": "Нижний Новгород",
      "pavlovo": "Павлово",
      "arzamas": "Саров",
      "sergac": "Сергач",
      "sakunja": "Шахунья",
    }
  },
  "novgorod-area": {
    name: "Новгородская область",
    city: {
      "valday": "Валдай",
      "novgorod": "Великий Новгород",
    }
  },
  "novosibirsk-area": {
    name: "Новосибирская область",
    city: {
      "bagan": "Баган",
      "barabinsk": "Барабинск",
      "bolotnoe": "Болотное",
      "vengerovo": "Венгерово",
      "dovolnoe": "Довольное",
      "zdvinsk": "Здвинск",
      "iskitim": "Искитим",
      "karasuk": "Карасук",
      "kargat": "Каргат",
      "kolyvan": "Колывань",
      "kocenevo": "Коченёво",
      "kochki": "Кочки",
      "krasnozerskoye": "Краснозерское",
      "krescenka": "Крещенка",
      "kupino": "Купино",
      "kystovka": "Кыштовка",
      "masljanino": "Маслянино",
      "moskovo": "Мошково",
      "novosibirsk": "Новосибирск",
      "obskaja-gmo": "Обская ГМО",
      "ogurcovo": "Огурцово",
      "ordynskoe": "Ордынское",
      "posevnaja": "Посевная",
      "severnoe": "Северное",
      "suzun": "Сузун",
      "tatarsk": "Татарск",
      "togucin": "Тогучин",
      "tolmachevo": "Толмачево",
      "ubinskoe": "Убинское",
      "uzhaniha": "Ужаниха",
      "ust-tarka": "Усть-Тарка",
      "cany": "Чаны",
      "chistoozernoe": "Чистоозерное",
      "culym": "Чулым",
    }
  },
  "omsk-area": {
    name: "Омская область",
    city: {
      "bolsherece": "Большеречье",
      "bolsie-uki": "Большие Уки",
      "isilkul": "Исилькуль",
      "kalachinsk": "Калачинск",
      "nazyuvaevsk": "Называевск",
      "odesskoe": "Одесское",
      "omsk": "Омск",
      "pavlogradka": "Павлоградка",
      "poltavka": "Полтавка",
      "pusskaja-polja": "Русская Поляна",
      "sargatskoe": "Саргатское",
      "tara": "Тара",
      "tevriz": "Тевриз",
      "tjukalinsk": "Тюкалинск",
      "ust-isim": "Усть-Ишим",
      "cerlak": "Черлак",
      "serbakul": "Шербакуль",
    }
  },
  "orenburg-area": {
    name: "Оренбургская область",
    city: {
      "buguruslan": "Бугуруслан",
      "busuluk": "Бузулук",
      "orenburg": "Оренбург",
    }
  },
  "oryol-area": {
    name: "Орловская область",
    city: {
      "bolhov": "Болхов",
      "verhove": "Верховье",
      "dmitrovsk-orlo": "Дмитровск-Орловский",
      "livny": "Ливны",
      "mcensk": "Мценск",
      "orel": "Орел",
    }
  },
  "penza-area": {
    name: "Пензенская область",
    city: {
      "gorodisce": "Городище",
      "zemetchino": "Земетчино",
      "pacelma": "Пачелма",
      "penza": "Пенза",
      "serdobsk": "Сердобск",
    }
  },
  "perm-area": {
    name: "Пермский край",
    city: {
      "berezniki": "Березники",
      "biser2": "Бисер",
      "verescagino2": "Верещагино",
      "gajny": "Гайны",
      "gubaha": "Губаха",
      "kosa": "Коса",
      "kochevo": "Кочево",
      "kudymkar": "Кудымкар",
      "kungur": "Кунгур",
      "lysva": "Лысьва",
      "nozovka": "Ножовка",
      "oca": "Оса",
      "ohansk": "Оханск",
      "perm": "Пермь",
      "chajkovskij": "Чайковский",
      "cerdyn": "Чердынь",
      "cermoz": "Чермоз",
      "cernuska": "Чернушка",
    }
  },
  "primorski-krai": {
    name: "Приморский край",
    city: {
      "agzu": "Агзу",
      "anucino": "Анучино",
      "arsenev": "Арсеньев",
      "artem": "Артем",
      "astrahanka": "Астраханка",
      "barabash": "Барабаш",
      "bereznjaki": "Березняки",
      "vladivostok": "Владивосток",
      "gamov": "Гамов",
      "glubinnoe": "Глубинное",
      "dalnerecensk": "Дальнереченск",
      "zolotoj": "Золотой",
      "kavalerovo": "Кавалерово",
      "kirovskij": "Кировский",
      "krasnyj-jar2": "Красный Яр",
      "laso": "Лазо",
      "lesozavodsk": "Лесозаводск",
      "malaja-kema": "Малая кема",
      "malinovo": "Малиново",
      "margaritovo": "Маргаритово",
      "melnichnoe": "Мельничное",
      "nahodka": "Находка",
      "olga": "Ольга",
      "ohotnichij": "Охотничий",
      "partizansk": "Партизанск",
      "pogranicnyj": "Пограничный",
      "poltavka2": "Полтавка",
      "poset": "Посьет",
      "preobrazhenie": "Преображение",
      "rodnikovaja": "Родниковая",
      "roscino": "Рощино",
      "rudnaj-pristan": "Рудная Пристань",
      "samarka": "Самарка",
      "svijagino": "Свиягино",
      "sosunovo": "Сосуново",
      "terehovka": "Тереховка",
      "ternej": "Терней",
      "timirjazevskij": "Тимирязевский",
      "turij-rog": "Турий Рог",
      "ussuriysk": "Уссурийск",
      "hkorol": "Хороль",
      "cuguevka": "Чугуевка",
      "jakovlevka": "Яковлевка",
    }
  },
  "pskov-area": {
    name: "Псковская область",
    city: {
      "velikie-luki": "Великие Луки",
      "gdov": "Гдов",
      "dno": "Дно",
      "opochka": "Опочка",
      "pskov": "Псков",
      "puskinskie-gor": "Пушкинские Горы",
    }
  },
  "rostov-area": {
    name: "Ростовская область",
    city: {
      "bokovskaja": "Боковская",
      "gigant": "Гигант",
      "zernograd": "Зерноград",
      "zimovniki": "Зимовники",
      "kazanskaja": "Казанская",
      "kamensk-sahtin": "Каменск-Шахтинский",
      "konstantinovsk": "Константиновск",
      "matveev-kurgan": "Матвеев Курган",
      "millerovo": "Миллерово",
      "morozovsk": "Морозовск",
      "remontnoe": "Ремонтное",
      "rostov-na-donu": "Ростов-на-Дону",
      "salsk": "Сальск",
      "taganrog": "Таганрог",
      "celina": "Целина",
      "cimljansk": "Цимлянск",
      "certkovo": "Чертково",
      "sahty": "Шахты",
    }
  },
  "ryazan-area": {
    name: "Рязанская область",
    city: {
      "elatma": "Елатьма",
      "pavelec": "Павелец",
      "rjazsk": "Ряжск",
      "rjazan": "Рязань",
      "sasovo": "Сасово",
      "tuma": "Тума",
    }
  },
  "samara-area": {
    name: "Самарская область",
    city: {
      "bolshaya-glushitsa": "Большая Глушица",
      "krasnoe-posele": "Красное поселение",
      "samara": "Самара",
      "syzran": "Сызрань",
      "toljati": "Тольятти",
      "celno-versiny": "Челно-Вершины",
    }
  },
  "saratov-area": {
    name: "Саратовская область",
    city: {
      "aleksandrov-ga": "Александров-Гай",
      "balakovo": "Балаково",
      "balasov": "Балашов",
      "ersov": "Ершов",
      "kalininsk": "Калининск",
      "krasnyj-kut": "Красный Кут",
      "ozinki": "Озинки",
      "pereljub": "Перелюб",
      "petrovsk": "Петровск",
      "pugacev": "Пугачев",
      "rtiscevo": "Ртищево",
      "saratov": "Саратов",
      "hvalynsk": "Хвалынск",
    }
  },
  "republic-saha-yakutia": {
    name: "Саха(Якутия) республика",
    city: {
      "agajakan": "Агаякан",
      "aihal": "Айхал",
      "aldan": "Алдан",
      "allah-jun": "Аллах-Юнь",
      "amga": "Амга",
      "anabar": "Анабар",
      "andrjushkino": "Андрюшкино",
      "batagay": "Батагай",
      "batagaj-alyta": "Батагай-Алыта",
      "batamaj": "Батамай",
      "belaja-gora": "Белая Гора",
      "berdigestjah": "Бердигестях",
      "bestjahskaja-s": "Бестяхск",
      "borogoncy": "Борогонцы",
      "buhta-ambarcik": "Бухта Амбарчик",
      "bujaga": "Буяга",
      "verhneviljujsk": "Верхневилюйск",
      "verhojansk": "Верхоянск",
      "verhojanskij-p": "Верхоянский Перевоз",
      "viljujsk": "Вилюйск",
      "vitim": "Витим",
      "vostochnaja": "Восточная",
      "deljankir": "Делянкир",
      "deputatskij": "Депутатский",
      "dzalinda": "Джалинда",
      "dzardzan": "Джарджан",
      "dzhikimda": "Джикимда",
      "dorozhnyi": "Дорожный",
      "zhigansk": "Жиганск",
      "zyrjanka": "Зырянка",
      "indigirskaja": "Индигирская",
      "isit": "Исить",
      "iema": "Иэма",
      "kanku": "Канку",
      "killer": "Килеер",
      "komaka": "Комака",
      "krest-haldzha": "Крест-Хальджай",
      "krestjah": "Крестях",
      "kjusjur": "Кюсюр",
      "lensk": "Ленск",
      "macha": "Мача",
      "mirnvj": "Мирный",
      "mys-kigiljach": "Мыс Кигилях",
      "mys-salaurova": "Мыс Салаурова",
      "nagornyj": "Нагорный",
      "namcy": "Намцы",
      "neryungry": "Нерюнгри",
      "nignejansk": "Нижнеянск",
      "njurba": "Нюрба",
      "njuja": "Нюя",
      "ojmjakon": "Оймякон",
      "olekminsk": "Олекминск",
      "olenek": "Оленек",
      "ostrov-preobra": "Остров Преображения",
      "o-va-dunaj": "Острова Дунай",
      "ohotskij-perev": "Охотский Перевоз",
      "pokrovskaja": "Покровская",
      "poljarnyj": "Полярный",
      "sangary": "Сангары",
      "sanyjahtat": "Саныяхтат",
      "saskylah": "Саскылах",
      "segen-kjuel": "Сеген-Кюель",
      "sogo-haja": "Сого-Хая",
      "srednekolymsk": "Среднеколымск",
      "stolb": "Столб",
      "suntar": "Сунтар",
      "suon-tit": "Суон-Тит",
      "suhana": "Сухана",
      "tajmylyr": "Таймылыр",
      "tegultja": "Тегультя",
      "teplyi-kljuch": "Теплый Ключ",
      "tiksi": "Тикси",
      "toko": "Токо",
      "tommot": "Томмот",
      "tompo": "Томпо",
      "tongulah": "Тонгулах",
      "tuoj-haja": "Туой-Хая",
      "tjumeti": "Тюмети",
      "tjanja": "Тяня",
      "ugino": "Угино",
      "ust-maja": "Усть-Мая",
      "ust-mil": "Усть-Миль",
      "ust-moma": "Усть-Мома",
      "nera": "Усть-Нера",
      "ust-charky": "Усть-Чаркы",
      "ust-judoma": "Усть-Юдома",
      "uchur": "Учур",
      "habardino": "Хабардино",
      "hatyryk-homo": "Хатырык-Хомо",
      "chaingda": "Чаингда",
      "chernishevskij": "Чернышевский",
      "cerskij": "Черский",
      "cokurdah": "Чокурдах",
      "culman": "Чульман",
      "chumpuruk": "Чумпурук",
      "curapca": "Чурапча",
      "cjulbju": "Чюльбю",
      "selagoncy": "Шелагонцы",
      "ykymchan": "Ыныкчан",
      "ytyk-kel": "Ытык-Кель",
      "ejk": "Эйк",
      "jugorenok": "Югоренок",
      "jurty": "Юрты",
      "jakutsk": "Якутск",
      "jansk": "Янск",
      "jarolin": "Ярольин",
    }
  },
  "sakhalin-area": {
    name: "Сахалинская область",
    city: {
      "aleksandrovsk-": "Александровск-Сахалинский",
      "val": "Вал",
      "ilyinskiy": "Ильинский",
      "komrvo": "Комрво",
      "korsakov": "Корсаков",
      "kurilsk": "Курильск",
      "moneron": "Монерон",
      "mys-terpenija": "Мыс Терпения",
      "nevelsk": "Невельск",
      "novikovo": "Новиково",
      "nogliki": "Ноглики",
      "nyvrovo": "Ныврово",
      "oha": "Оха",
      "pilvo": "Пильво",
      "pogibi": "Погиби",
      "pogranicnoe": "Пограничное",
      "poronajsk": "Поронайск",
      "severo-kurils": "Северо-Курильск",
      "simusir": "Симушир",
      "uglegorsk": "Углегорск",
      "urup": "Уруп",
      "holmsk": "Холмск",
      "juzno-kurilsk": "Южно-Курильск",
      "juzhno-sahalin": "Южно-Сахалинск",
    }
  },
  "sverdlovsk-area": {
    name: "Свердловская область",
    city: {
      "alapaevsk": "Алапаевск",
      "artenovsky": "Артемовский",
      "bisert": "Бисерть",
      "verhnee-dubrov": "Верхнее Дуброво",
      "verhoture": "Верхотурье",
      "visim": "Висим",
      "gari": "Гари",
      "ekaterinburg": "Екатеринбург",
      "ivdel": "Ивдель",
      "irbit-fomino": "Ирбит-Фомино",
      "kamensk-uralsk": "Каменск-Уральский",
      "kamyslov": "Камышлов",
      "kolcovo": "Кольцово",
      "krasnoufimsk": "Красноуфимск",
      "kushva": "Кушва",
      "kytlym": "Кытлым",
      "mihajlovskoe": "Михайловск",
      "nevjansk": "Невьянск",
      "nizhnyj-tagil": "Нижний Тагил",
      "ponil": "Понил",
      "revda": "Ревда",
      "severouralsk": "Североуральск",
      "serov2": "Серов",
      "syrert": "Сысерть",
      "tabory": "Таборы",
      "tavda": "Тавда",
      "tugulym": "Тугулым",
      "turinsk": "Туринск",
      "samary": "Шамары",
    }
  },
  "republic-northern-ossetia": {
    name: "Северная Осетия-Алания республика",
    city: {
      "vladikavkaz": "Владикавказ",
      "mozdok": "Моздок",
    }
  },
  "smolensk-area": {
    name: "Смоленская область",
    city: {
      "vladikavkaz": "Владикавказ",
      "mozdok": "Моздок",
    }
  },
  "stavropol-territory": {
    name: "Ставропольский край",
    city: {
      "aleksandrovsko2": "Александровское",
      "arzgir": "Арзгир",
      "blagodarnyj": "Благодарный",
      "budennovsk": "Буденновск",
      "divnoe": "Дивное",
      "essentuki": "Ессентуки",
      "jeleznovodsk": "Железноводск",
      "kislovodsk": "Кисловодск",
      "krasnogvardejs": "Красногвардейское",
      "mineralnye-vo": "Минеральные воды",
      "nevinnomissk": "Невинномысск",
      "novoaleksandrovsk": "Новоалександровск",
      "pjatigorsk": "Пятигорск",
      "roscino2": "Рощино",
      "svetlograd": "Светлоград",
      "stavropol": "Ставрополь",
    }
  },
  "tambov-area": {
    name: "Тамбовская область",
    city: {
      "zerdevka": "Жердевка",
      "kirsanov": "Кирсанов",
      "micurinsk": "Мичуринск",
      "morsansk": "Моршанск",
      "oblovka": "Обловка",
      "sovchoz-im-len": "Совхоз им.Ленина",
      "tambov": "Тамбов",
    }
  },
  "republic-tatarstan": {
    name: "Татарстан республика",
    city: {
      "bolshie-kajbi": "Большие Кайбицы",
      "bugulma": "Бугульма",
      "elabuga": "Елабуга",
      "kasan": "Казань",
      "laishevo": "Лаишево",
      "musljumovo": "Муслюмово",
      "naberchelny": "Набережные Челны",
      "tetjusi": "Тетюши",
      "chistopol": "Чистополь",
      "culpanovo": "Чулпаново",
    }
  },
  "tver-area": {
    name: "Тверская область",
    city: {
      "belyj": "Белый",
      "bologoe": "Бологое",
      "vysnij-volocek": "Вышний Волочек",
      "kasin": "Кашин",
      "krasnyj-holm": "Красный Холм",
      "maksatiha": "Максатиха",
      "ostaskov": "Осташков",
      "rzev": "Ржев",
      "stariza": "Старица",
      "tver": "Тверь",
      "torzhok": "Торжок",
      "toropez": "Торопец",
    }
  },
  "tomsk-area": {
    name: "Томская область",
    city: {
      "aleksandrovsko": "Александровское",
      "bakchar": "Бакчар",
      "baturino": "Батурино",
      "belyj-jar": "Белый Яр",
      "berezovka": "Березовка",
      "vanzil-kynak": "Ванжиль-Кынак",
      "kargasok": "Каргасок",
      "kozevnikovo": "Кожевниково",
      "kolpasevo": "Колпашево",
      "krasnyj-jar": "Красный Яр",
      "majsk": "Майск",
      "molchanovo": "Молчаново",
      "napas": "Напас",
      "novyj-vasjugan": "Новый Васюган",
      "parabel": "Парабель",
      "pervomajskoe": "Первомайское",
      "podgornoe": "Подгорное",
      "prohorenko": "Прохоркино",
      "pudino": "Пудино",
      "sredny-vasjuga": "Средний Васюган",
      "starica": "Старица",
      "stepanovka": "Степановка",
      "tegulden": "Тегульдет",
      "tomsk": "Томск",
      "ust-ozernoe": "Усть-Озерное",
    }
  },
  "tula-area": {
    name: "Тульская область",
    city: {
      "volovo": "Волово",
      "efremov": "Ефремов",
      "novomoskovsk": "Новомосковск",
      "tula": "Тула",
    }
  },
  "republic-tyva": {
    name: "Тыва республика",
    city: {
      "kyzyl": "Кызыл",
      "mugur-aksy": "Мугур-Аксы",
      "saryg-sep": "Сарыг-Сеп",
      "sosnovka2": "Сосновка",
      "toora-hem": "Тоора-Хем",
      "havu-aksy": "Хову-Аксы",
      "chadan": "Чадан",
      "ersin": "Эрзин",
    }
  },
  "tyumen-area": {
    name: "Тюменская область",
    city: {
      "abatskij": "Абатский",
      "vahovsk": "Ваховск",
      "vikulovo": "Викулово",
      "golyshmanovo": "Голышманово",
      "demjanskoe": "Демьянское",
      "isim": "Ишим",
      "sladkovo": "Сладково",
      "tobolsk": "Тобольск",
      "tjumen": "Тюмень",
      "jalturovosk": "Ялуторовск",
    }
  },
  "republic-udmurtia": {
    name: "Удмуртия республика",
    city: {
      "votkinsk": "Воткинск",
      "glazov": "Глазов",
      "debessy": "Дебессы",
      "izhevsk": "Ижевск",
      "mozga": "Можга",
      "sarapul": "Сарапул",
      "selty": "Селты",
    }
  },
  "ulyanovsk-area": {
    name: "Ульяновская  область",
    city: {
      "inza": "Инза",
      "kanadei": "Канадей",
      "ulyanovsk": "Ульяновск",
    }
  },
  "khabarovsk-territory": {
    name: "Хабаровский край",
    city: {
      "ajan": "Аян",
      "bajdukov": "Байдуков",
      "baktor": "Бактор",
      "baladek": "Баладек",
      "batomga": "Батомга",
      "bikin": "Бикин",
      "bicevaja": "Бичевая",
      "bogorodskoe": "Богородское",
      "burukan": "Бурукан",
      "verhove-urmi": "Верховье Умри",
      "veselaja-gorka": "Веселая Горка",
      "vjazemskaja": "Вяземский",
      "gvasjugi": "Гвасюги",
      "georgievka": "Георгиевка",
      "gorin": "Горин",
      "guga": "Гуга",
      "dzhana": "Джана",
      "ekaterino-niko": "Екатерино-Никольское",
      "im-poliny-osip": "Им. Полины Осипенко",
      "ioli": "Иоли",
      "komsomolsk-na": "Комсомольск-на-Амуре",
      "kur": "Кур",
      "kurun-urjah": "Курун-Урях",
      "leninskoe": "Ленинское",
      "lermontovka": "Лермонтовка",
      "litke": "Литке",
      "mopau": "Мопау",
      "nelkan": "Нелькан",
      "nizhne-tambovs": "Нижне-Тамбовское",
      "nikolaevsk-na-": "Николаевск-на-Амуре",
      "obluce": "Облучье",
      "ostrov-bolsoj": "Остров Большой Шантар",
      "ohotsk": "Охотск",
      "segzhema": "Сегжема",
      "sektagli": "Сектагли",
      "smidovic": "Смидович",
      "sovetskaja-gav": "Советская Гавань",
      "solekul": "Солекуль",
      "sofijskij-prii": "Софийский Прииск",
      "sukpaj": "Сукпай",
      "tivjaku": "Тивяку",
      "troickoe2": "Троицкое",
      "tumnin": "Тумнин",
      "udskoe": "Удское",
      "ulja": "Улья",
      "urmi": "Урми",
      "ust-umalta": "Усть-Умальта",
      "habarovsk": "Хабаровск",
      "hularin": "Хуларин",
      "cimmermanovka": "Циммермановка",
      "cekunda": "Чекунда",
      "chumikan": "Чумикан",
      "enkan": "Энкан",
    }
  },
  "republic-khakassia": {
    name: "Хакасия республика",
    city: {
      "abakan": "Абакан",
      "askiz": "Аскиз",
      "beja": "Бея",
      "bolshoj-on": "Большой Он",
      "kommunar": "Коммунар",
      "nenastnaja": "Ненастная",
      "neozhidannyj": "Неожиданный",
      "pervomajskoe2": "Первомайское",
      "tastyp": "Таштып",
      "hakasskaja": "Хакасская",
      "cheremushki": "Черемушки",
      "sira": "Шира",
    }
  },
  "hanty-mansijskij-ar": {
    name: "Ханты-Мансийский автономный округ",
    city: {
      "altaj": "Алтай",
      "berezovo": "Березово",
      "vonegan": "Воньеган",
      "igrim": "Игрим",
      "kasym": "Казым",
      "kogalym": "Когалым",
      "kuminskaja": "Куминская",
      "larjak": "Ларьяк",
      "leusi": "Леуши",
      "neftejugansk": "Нефтеюганск",
      "niznevartovsk": "Нижневартовск",
      "nizhnesortymsk": "Нижнесортымск",
      "njaksimvol": "Няксимволь",
      "oktjabrskoe": "Октябрьское",
      "raduzhyi": "Радужный",
      "saran-paul": "Саранпауль",
      "sosva": "Сосьва",
      "surgut": "Сургут",
      "sytomino": "Сытомино",
      "taurovo": "Таурово",
      "ugut": "Угут",
      "hanty-mansijsk": "Ханты-Мансийск",
      "saim": "Шаим",
      "julsk": "Юильск",
    }
  },
  "chelyabinsk-area": {
    name: "Челябинская область",
    city: {
      "argajash": "Аргаяш",
      "bredy": "Бреды",
      "brodokalmak": "Бродокалмак",
      "verhnij-ufalej": "Верхний Уфалей",
      "zlatoust": "Златоуст",
      "kartaly": "Карталы",
      "katav-ivanovsk": "Катав-Ивановск",
      "kizilskoe": "Кизильское",
      "komsomolec": "Комсомолец",
      "magnitogorsk": "Магнитогорск",
      "miass": "Миасс",
      "njazepetrovsk": "Нязепетровск",
      "ozersck": "Озерск",
      "troizk": "Троицк",
      "cheljabinsk": "Челябинск",
      "juzhnouralsk": "Южноуральск",
    }
  },
  "chechen-republic": {
    name: "Чеченская республика",
    city: {
      "groznyj": "Грозный",
    }
  },
  "chuvash-republic": {
    name: "Чувашская республика",
    city: {
      "alatyr": "Алатырь",
      "kanas": "Канаш",
      "cebokcary": "Чебоксары",
    }
  },
  "chukotskij-ar": {
    name: "Чукотский автономный округ",
    city: {
      "anadyr": "Анадырь",
      "baraniha": "Бараниха",
      "berezovo2": "Березово",
      "bilibino": "Билибино",
      "biser": "Бисер",
      "buhta-providen": "Бухта Провидения",
      "valjkarkaij": "Валькаркай",
      "ilirnej": "Илирней",
      "korkodon": "Коркодон",
      "markovo": "Марково",
      "mys-billingsa": "Мыс Биллингса",
      "mys-uelen": "Мыс Уэлен",
      "mys-smidta": "Мыс Шмидта",
      "omolon": "Омолон",
      "o-ajon": "Остров  Айон",
      "pevek": "Певек",
      "serov": "Серов",
      "tanjuer": "Танюрер",
      "ust-oloj": "Усть-Олой",
      "chaun": "Чаун",
      "egvekinot": "Эгвекинот",
      "enmuveem": "Эньмувеем",
    }
  },
  "jamalo-nenetskij-ar": {
    name: "Ямало-Ненецкий автономный округ",
    city: {
      "antipajuta": "Антипаюта",
      "gydojmo": "Гыдоямо",
      "krasnoselkups": "Красноселькупск",
      "maresalja": "Марресаля",
      "morgevaj": "Моржовая",
      "muzi": "Мужи",
      "nadym": "Надым",
      "novyi-port": "Новый Порт",
      "novyi-urengoi": "Новый Уренгой",
      "nojabrsk": "Ноябрьск",
      "nyda": "Ныда",
      "o-wilkickogo": "Остров  Вилькицкого",
      "pangody": "Пангоды",
      "pitljar": "Питляр",
      "polui": "Полуй",
      "ra-iz": "Ра-Из",
      "salemal": "Салемал",
      "salehard": "Салехард",
      "sejxa": "Сеяха",
      "sidorovsk": "Сидоровск",
      "tazovskiy": "Тазовский",
      "tambej": "Тамбей",
      "tarko-sale": "Тарко-Сале",
      "tilka": "Толька",
    }
  },
  "yaroslavl-area": {
    name: "Ярославская область",
    city: {
      "pereslavl-zal": "Переславль-Залесский",
      "poshekhonie": "Пошехонье",
      "rostov": "Ростов",
      "rybinsk": "Рыбинск",
      "jaroslavl": "Ярославль",
    }
  }
};



  

