# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.lstbknd.net:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.lstbknd.net
    container_name: orderer.lstbknd.net
    networks:
      - byfn

  peer0.ci.lstbknd.net:
    container_name: peer0.ci.lstbknd.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ci.lstbknd.net
    networks:
      - byfn

  peer1.ci.lstbknd.net:
    container_name: peer1.ci.lstbknd.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ci.lstbknd.net
    networks:
      - byfn

  peer0.cd.lstbknd.net:
    container_name: peer0.cd.lstbknd.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.cd.lstbknd.net
    networks:
      - byfn

  peer1.cd.lstbknd.net:
    container_name: peer1.cd.lstbknd.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.cd.lstbknd.net
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ci.lstbknd.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/lastbackend/monarch/contrib/network/crypto-config/peerOrganizations/ci.lstbknd.net/peers/peer0.ci.lstbknd.net/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/lastbackend/monarch/contrib/network/crypto-config/peerOrganizations/ci.lstbknd.net/peers/peer0.ci.lstbknd.net/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/lastbackend/monarch/contrib/network/crypto-config/peerOrganizations/ci.lstbknd.net/peers/peer0.ci.lstbknd.net/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/lastbackend/monarch/contrib/network/crypto-config/peerOrganizations/ci.lstbknd.net/users/Admin@ci.lstbknd.net/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - /opt/src/github.com/lastbackend:/opt/gopath/src/github.com/lastbackend
    depends_on:
      - orderer.lstbknd.net
      - peer0.ci.lstbknd.net
      - peer1.ci.lstbknd.net
      - peer0.cd.lstbknd.net
      - peer1.cd.lstbknd.net
    networks:
      - byfn

