# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.lstbknd.net:
    container_name: orderer.lstbknd.net
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/lstbknd.net/orderers/orderer.lstbknd.net/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/lstbknd.net/orderers/orderer.lstbknd.net/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.ci.lstbknd.net:
    container_name: peer0.ci.lstbknd.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ci.lstbknd.net
      - CORE_PEER_ADDRESS=peer0.ci.lstbknd.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ci.lstbknd.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ci.lstbknd.net/peers/peer0.ci.lstbknd.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ci.lstbknd.net/peers/peer0.ci.lstbknd.net/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.ci.lstbknd.net:
    container_name: peer1.ci.lstbknd.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.ci.lstbknd.net
      - CORE_PEER_ADDRESS=peer1.ci.lstbknd.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ci.lstbknd.net:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ci.lstbknd.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ci.lstbknd.net/peers/peer1.ci.lstbknd.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ci.lstbknd.net/peers/peer1.ci.lstbknd.net/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer0.cd.lstbknd.net:
    container_name: peer0.cd.lstbknd.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.cd.lstbknd.net
      - CORE_PEER_ADDRESS=peer0.cd.lstbknd.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cd.lstbknd.net:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cd.lstbknd.net:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cd.lstbknd.net/peers/peer0.cd.lstbknd.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cd.lstbknd.net/peers/peer0.cd.lstbknd.net/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer1.cd.lstbknd.net:
    container_name: peer1.cd.lstbknd.net
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.cd.lstbknd.net
      - CORE_PEER_ADDRESS=peer1.cd.lstbknd.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.cd.lstbknd.net:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.cd.lstbknd.net:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cd.lstbknd.net/peers/peer1.cd.lstbknd.net/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cd.lstbknd.net/peers/peer1.cd.lstbknd.net/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
